#!/bin/sh
set -e

CONFIG_DIR="${VELOCITY_CONFIG_DIR:-/opt/velocity/config}"
PLUGIN_DIR="${VELOCITY_PLUGIN_DIR:-/opt/velocity/plugins}"
VELOCITY_PORT="${VELOCITY_PORT:-25577}"
VELOCITY_BIND="${VELOCITY_BIND:-0.0.0.0}"
VELOCITY_MOTD="${VELOCITY_MOTD:-A Velocity Proxy}"

mkdir -p "$CONFIG_DIR" "$PLUGIN_DIR"

if [ ! -f "$CONFIG_DIR/velocity.toml" ]; then
    cat > "$CONFIG_DIR/velocity.toml" << EOF
# Velocity configuration
# Automatically generated by Docker entrypoint

config-version = "2.8"

bind = "${VELOCITY_BIND}:${VELOCITY_PORT}"
motd = "${VELOCITY_MOTD}"
show-max-players = ${VELOCITY_SHOW_MAX_PLAYERS:-500}

player-info-forwarding-mode = "${VELOCITY_FORWARDING_MODE:-NONE}"
forwarding-secret-file = "${CONFIG_DIR}/forwarding.secret"

announce-proxy-commands = ${VELOCITY_ANNOUNCE_COMMANDS:-false}

[servers]
# Configure your backend servers here:
# try = [
#     { host = "localhost", port = 25566, name = "lobby" }
# ]

[forced-hosts]
# Configure forced hosts here:
# "lobby.example.com" = "lobby"
EOF
    echo "Generated default velocity.toml"
fi

cd /opt/velocity
exec java -Xms"${VELOCITY_MEMORY:-256M}" -Xmx"${VELOCITY_MEMORY:-512M}" \
    -Dvelocity.config="$CONFIG_DIR/velocity.toml" \
    -jar velocity.jar
